const candidate = (id, title, weight = 50, extra = {}) => ({
  id,
  title,
  weight,
  available: true,
  countries: ["*"],
  languages: ["*"],
  timeRanges: ["all"],
  ...extra,
});

export const MODULE_CONFIG = {
  moduleVersion: "mood_intent_v1_2",
  enabled: true,
  experimentGroup: "treatment",
  playlistSource: "existing_youtube_music",
  intents: [
    {
      id: "focus",
      icon: "▤",
      tint: "#e7edff",
      labels: { es: "Concentrarme", pt: "Focar", en: "Focus" },
      hints: { es: "Estudio y trabajo", pt: "Estudo e trabalho", en: "Study and work" },
      playlistPool: [
        candidate("PLu7El_KDcFbP43to4PtAikjbsmZRdKBIL", "Focus & Study Music", 60),
        candidate("PLu7El_KDcFbNRrI5_5BjdVgGArEvpSxvO", "Lofi Beats", 40),
      ],
      fallbackPool: [
        candidate("PLu7El_KDcFbMwqBphwJUG8Zw0SbbS-TPK", "Classical Reading"),
      ],
      refineOptions: ["softer", "noLyrics", "shuffle"],
    },
    {
      id: "relax",
      icon: "≈",
      tint: "#e1f7ec",
      labels: { es: "Relajarme", pt: "Relaxar", en: "Relax" },
      hints: { es: "Bajar el ritmo", pt: "Desacelerar", en: "Slow things down" },
      playlistPool: [
        candidate("PLu7El_KDcFbNRkPL1ZRQ3I4xkhFoACo-K", "Chill Hits", 55),
        candidate("PLu7El_KDcFbPdz3Dt1ortWnGokQzuXLew", "Chill Latin Music", 45, { countries: ["MX", "BR", "CO", "*"] }),
      ],
      fallbackPool: [
        candidate("PLu7El_KDcFbNYtg7RAEdo1QXN1VYSXpUE", "Relax Brunch"),
      ],
      refineOptions: ["softer", "moreLatin", "shuffle"],
    },
    {
      id: "energy",
      icon: "ϟ",
      tint: "#fff1c9",
      labels: { es: "Subir energía", pt: "Ganhar energia", en: "Boost energy" },
      hints: { es: "Activarme ahora", pt: "Me animar agora", en: "Get moving now" },
      playlistPool: [
        candidate("PLu7El_KDcFbPmzSPJR8J1cBa8nY4MZ6XE", "Best Workout Music", 55),
        candidate("PLu7El_KDcFbMQiwNT-rapA_IqJ62YtnD3", "Beast Mode", 45),
      ],
      fallbackPool: [
        candidate("PLu7El_KDcFbPcrXVUnCSMy9MWpKKkLYnb", "Mood Booster"),
      ],
      refineOptions: ["higherEnergy", "moreReggaeton", "shuffle"],
    },
    {
      id: "party",
      icon: "✦",
      tint: "#ffe5ef",
      labels: { es: "Fiesta", pt: "Festa", en: "Party" },
      hints: { es: "Bailar y celebrar", pt: "Dançar e celebrar", en: "Dance and celebrate" },
      playlistPool: [
        candidate("PLu7El_KDcFbN5h0mCi5vMycX1_OnOL-Kc", "Best Party Music", 60),
        candidate("PLu7El_KDcFbPcSV6hn-h9AAK49nla9CdB", "Brazilian Funk Party", 40, { countries: ["BR", "MX", "CO", "*"] }),
      ],
      fallbackPool: [
        candidate("PLu7El_KDcFbMt59n6fNtuggiEccEnt1Bz", "Shout-Out Party Hits"),
      ],
      refineOptions: ["higherEnergy", "moreReggaeton", "shuffle"],
    },
    {
      id: "release",
      icon: "♡",
      tint: "#eee7ff",
      labels: { es: "Desahogarme", pt: "Desabafar", en: "Let it out" },
      hints: { es: "Sentir y soltar", pt: "Sentir e soltar", en: "Feel it through" },
      playlistPool: [
        candidate("PLu7El_KDcFbOORkuDwVp8xESIGsJUmpEE", "Sad Latin Songs", 55),
        candidate("PLu7El_KDcFbNPDkST7ZFOCkLK_cM0rQOJ", "Best Breakup Songs", 45),
      ],
      fallbackPool: [
        candidate("PLu7El_KDcFbNoOYrrs0DO2qUroFafyRY4", "Late Night Blues"),
      ],
      refineOptions: ["sadder", "liftMe", "shuffle"],
    },
    {
      id: "sleep",
      icon: "☾",
      tint: "#e2efff",
      labels: { es: "Dormir", pt: "Dormir", en: "Sleep" },
      hints: { es: "Bajar estímulos", pt: "Menos estímulo", en: "Wind down gently" },
      playlistPool: [
        candidate("PLu7El_KDcFbPt_q3YjQ1CFVuJMm27GNyF", "Classical for Sleeping", 55, { timeRanges: ["night", "all"] }),
        candidate("PLu7El_KDcFbMNCuyTnGlBvaaFvmmNUuup", "Rain Sounds", 45),
      ],
      fallbackPool: [
        candidate("PLu7El_KDcFbP_aibB35dgne-jSc5_7iQ0", "Daydreamer"),
      ],
      refineOptions: ["calmer", "whiteNoise", "shuffle"],
    },
  ],
};

const BASE_QUICK_KEYWORDS = {
  focus: ["study", "focus", "lofi", "reading"],
  relax: ["chill", "relaxed", "coffee", "jazz"],
  energy: ["workout", "gym", "high bpm", "motivational"],
  party: ["party", "dance", "edm", "carnival"],
  release: ["sad", "heartbreak", "breakup", "melancholic"],
  sleep: ["sleep", "rain", "peaceful", "white noise"],
};

export const QUICK_CATEGORIES = [
  ...MODULE_CONFIG.intents.map(intent => ({
    id: intent.id,
    intentId: intent.id,
    icon: intent.icon,
    tint: intent.tint,
    labels: intent.labels,
    hints: intent.hints,
    keywords: BASE_QUICK_KEYWORDS[intent.id],
  })),
  {
    id: "reggaeton",
    intentId: "party",
    icon: "♬",
    tint: "#ffe8d7",
    labels: { es: "Reggaeton", pt: "Reggaeton", en: "Reggaeton" },
    hints: { es: "Ritmo latino", pt: "Ritmo latino", en: "Latin rhythm" },
    keywords: ["reggaeton"],
  },
  {
    id: "latin",
    intentId: "party",
    icon: "💃",
    tint: "#fff1c9",
    labels: { es: "Ritmos latinos", pt: "Ritmos latinos", en: "Latin vibes" },
    hints: { es: "Salsa y cumbia", pt: "Salsa e cumbia", en: "Salsa and cumbia" },
    keywords: ["latin", "salsa", "cumbia"],
  },
  {
    id: "romance",
    intentId: "relax",
    icon: "♥",
    tint: "#ffe5ef",
    labels: { es: "Romántico", pt: "Romântico", en: "Romantic" },
    hints: { es: "Amor y citas", pt: "Amor e encontros", en: "Love and date night" },
    keywords: ["romantic", "love", "date", "valentine"],
  },
  {
    id: "drive",
    intentId: "energy",
    icon: "◇",
    tint: "#e2efff",
    labels: { es: "En el auto", pt: "No carro", en: "Road trip" },
    hints: { es: "Música para manejar", pt: "Música para dirigir", en: "Windows down" },
    keywords: ["drive", "road trip", "driving", "windows-down"],
  },
  {
    id: "soccer",
    intentId: "party",
    icon: "⚽",
    tint: "#e1f7ec",
    labels: { es: "Fútbol", pt: "Futebol", en: "Soccer" },
    hints: { es: "Modo estadio", pt: "Modo estádio", en: "Stadium mode" },
    keywords: ["football", "soccer", "world cup", "fifa"],
  },
  {
    id: "kpop",
    intentId: "energy",
    icon: "★",
    tint: "#eee7ff",
    labels: { es: "K-Pop", pt: "K-Pop", en: "K-Pop" },
    hints: { es: "Hits y coreografías", pt: "Hits e coreografias", en: "Hits and choreography" },
    keywords: ["kpop", "k-pop"],
  },
  {
    id: "rock",
    intentId: "energy",
    icon: "♯",
    tint: "#ffe8d7",
    labels: { es: "Rock", pt: "Rock", en: "Rock" },
    hints: { es: "Guitarras y clásicos", pt: "Guitarras e clássicos", en: "Guitars and classics" },
    keywords: ["rock", "guitar"],
  },
  {
    id: "soundtracks",
    intentId: "focus",
    icon: "▰",
    tint: "#e7edff",
    labels: { es: "Cine y series", pt: "Filmes e séries", en: "Soundtracks" },
    hints: { es: "Bandas sonoras", pt: "Trilhas sonoras", en: "Movies and TV" },
    keywords: ["ost", "soundtrack", "movie", "film", "series", "anime"],
  },
  {
    id: "family",
    intentId: "relax",
    icon: "☀",
    tint: "#fff1c9",
    labels: { es: "Niños y familia", pt: "Crianças e família", en: "Family time" },
    hints: { es: "Para escuchar juntos", pt: "Para ouvir juntos", en: "Listen together" },
    keywords: ["kids", "family", "children", "disney"],
  },
  {
    id: "shower",
    intentId: "energy",
    icon: "≈",
    tint: "#e2efff",
    labels: { es: "En la ducha", pt: "No banho", en: "Shower time" },
    hints: { es: "Canta sin parar", pt: "Cante sem parar", en: "Sing it out" },
    keywords: ["shower"],
  },
];

export const COPY = {
  es: {
    eyebrow: "PARA ESTE MOMENTO",
    title: "¿Qué quieres escuchar ahora?",
    subtitle: "Empieza con un toque",
    assistantEntry: "¿No sabes qué escuchar? Te ayudo",
    playerEyebrow: "REPRODUCCIÓN EN LA APP",
    playerHeading: "Tu música empieza aquí",
    preparing: "Preparando música…",
    fallback: "Probando otra selección…",
    playing: "Reproduciendo para ti",
    autoplayBlocked: "Toca reproducir en el player de YouTube para empezar.",
    offline: "Sin conexión. Revisa tu red e inténtalo de nuevo.",
    unavailable: "No se pudo reproducir esta selección. Prueba otra.",
    retry: "Intentar de nuevo",
    browseEyebrow: "TU MUSIC TAB",
    browseTitle: "Lo más escuchado",
    youtubeDisclosure: "El contenido se reproduce con YouTube API Services.",
    nowPlaying: "En reproducción",
    assistantStep: step => `Paso ${step} de 2`,
    assistantMomentTitle: "¿Para qué momento?",
    assistantMomentSub: "Elige una opción. No hay formulario.",
    assistantEnergyTitle: "¿Qué energía buscas?",
    assistantEnergySub: "Al tocar, la música empieza de inmediato.",
    musicTab: "Music",
  },
  pt: {
    eyebrow: "PARA ESTE MOMENTO",
    title: "O que você quer ouvir agora?",
    subtitle: "Comece com um toque",
    assistantEntry: "Não sabe o que ouvir? Eu te ajudo",
    playerEyebrow: "REPRODUÇÃO NO APP",
    playerHeading: "Sua música começa aqui",
    preparing: "Preparando a música…",
    fallback: "Tentando outra seleção…",
    playing: "Tocando para você",
    autoplayBlocked: "Toque em reproduzir no player do YouTube para começar.",
    offline: "Sem conexão. Verifique sua rede e tente novamente.",
    unavailable: "Não foi possível tocar esta seleção. Tente outra.",
    retry: "Tentar novamente",
    browseEyebrow: "SUA MUSIC TAB",
    browseTitle: "Mais ouvidas",
    youtubeDisclosure: "O conteúdo é reproduzido com YouTube API Services.",
    nowPlaying: "Tocando agora",
    assistantStep: step => `Etapa ${step} de 2`,
    assistantMomentTitle: "Para qual momento?",
    assistantMomentSub: "Escolha uma opção. Não é um formulário.",
    assistantEnergyTitle: "Que energia você busca?",
    assistantEnergySub: "Ao tocar, a música começa na hora.",
    musicTab: "Music",
  },
  en: {
    eyebrow: "FOR THIS MOMENT",
    title: "What do you want to hear now?",
    subtitle: "Start with one tap",
    assistantEntry: "Not sure what to play? Help me choose",
    playerEyebrow: "IN-APP PLAYBACK",
    playerHeading: "Your music starts here",
    preparing: "Preparing your music…",
    fallback: "Trying another set…",
    playing: "Playing for you",
    autoplayBlocked: "Tap play in the YouTube player to start.",
    offline: "You’re offline. Check your connection and try again.",
    unavailable: "This set could not play. Try another one.",
    retry: "Try again",
    browseEyebrow: "YOUR MUSIC TAB",
    browseTitle: "Top right now",
    youtubeDisclosure: "Content plays through YouTube API Services.",
    nowPlaying: "Now playing",
    assistantStep: step => `Step ${step} of 2`,
    assistantMomentTitle: "What are you doing?",
    assistantMomentSub: "Pick one option. This is not a questionnaire.",
    assistantEnergyTitle: "What energy do you want?",
    assistantEnergySub: "Your tap starts the music right away.",
    musicTab: "Music",
  },
};

export const ASSISTANT_OPTIONS = {
  moments: [
    { id: "study", icon: "▤", labels: { es: "Estudio o trabajo", pt: "Estudo ou trabalho", en: "Study or work" } },
    { id: "drive", icon: "◇", labels: { es: "Manejando", pt: "Dirigindo", en: "Driving" } },
    { id: "workout", icon: "ϟ", labels: { es: "Entrenando", pt: "Treinando", en: "Working out" } },
    { id: "rest", icon: "≈", labels: { es: "Descansando", pt: "Descansando", en: "Resting" } },
    { id: "party", icon: "✦", labels: { es: "De fiesta", pt: "Em uma festa", en: "At a party" } },
    { id: "bedtime", icon: "☾", labels: { es: "Antes de dormir", pt: "Antes de dormir", en: "Bedtime" } },
  ],
  energies: [
    { id: "calm", icon: "≈", labels: { es: "Calma", pt: "Calma", en: "Calm" } },
    { id: "focus", icon: "◎", labels: { es: "Concentración", pt: "Foco", en: "Focus" } },
    { id: "happy", icon: "☀", labels: { es: "Feliz", pt: "Feliz", en: "Happy" } },
    { id: "high", icon: "ϟ", labels: { es: "Alta energía", pt: "Alta energia", en: "High energy" } },
    { id: "emotional", icon: "♡", labels: { es: "Emocional", pt: "Emocional", en: "Emotional" } },
  ],
};

export const REFINE_LABELS = {
  softer: { es: "Más suave", pt: "Mais suave", en: "Softer" },
  noLyrics: { es: "Sin letra", pt: "Sem letra", en: "No lyrics" },
  moreLatin: { es: "Más latino", pt: "Mais latino", en: "More Latin" },
  higherEnergy: { es: "Más energía", pt: "Mais energia", en: "More energy" },
  moreReggaeton: { es: "Más Reggaeton", pt: "Mais Reggaeton", en: "More Reggaeton" },
  sadder: { es: "Más sentimental", pt: "Mais sentimental", en: "More emotional" },
  liftMe: { es: "Quiero animarme", pt: "Quero me animar", en: "Lift me up" },
  calmer: { es: "Más tranquilo", pt: "Mais calmo", en: "Calmer" },
  whiteNoise: { es: "Ruido blanco", pt: "Ruído branco", en: "White noise" },
  shuffle: { es: "Cambiar selección", pt: "Trocar seleção", en: "Try another" },
};
